Repository oasisprotocol/sapphire-paratime, pull requests merged in 2023-10, with the labels that each got.

#193 Skip subcall delegation test
  contracts/test/subcall.ts
Labels: js

#200 Add Hardhat example script `run-vigil.ts` to CI
  .github/workflows/contracts-test.yaml
  examples/hardhat/scripts/run-vigil.ts
Labels: p:1, js

#203 Add publish workflow
  .github/workflows/publish.yaml
  CONTRIBUTING.md
  README.md
Labels: p:1, s:underway, github_actions, js

#175 contracts: submit pre-signed transaction
  clients/js/src/compat.ts
  contracts/contracts/tests/EIP155Tests.sol
  contracts/hardhat.config.ts
  contracts/package.json
  contracts/test/eip155.ts
  examples/onchain-signer/contracts/CommentBox.sol
  examples/onchain-signer/test/CommentBox.ts
  pnpm-lock.yaml
Labels: p:1, js

#206 Update Go dependencies
  clients/go/README.md
  clients/go/cipher.go
  clients/go/go.mod
  clients/go/go.sum
  runtime/README.md
Labels: p:1, dependencies, go

#208 examples/onchain-signer/test: Add support for Sapphire Testnet/Mainnet
  examples/onchain-signer/contracts/Gasless.sol
  examples/onchain-signer/hardhat.config.ts
  examples/onchain-signer/test/CommentBox.ts
Labels: p:1, s:underway, js, contracts

#204 README: added api-docs links
  README.md
Labels: p:2

#213 clients/js: bump package version to 1.1.2
  clients/js/package.json
Labels: js

#214 clients/js: bump to 1.1.3
  clients/js/package.json
Labels: js

#191 Remove Truffle support from TS client
  .github/workflows/ci-test.yaml
  .github/workflows/contracts-test.yaml
  clients/js/src/compat.ts
  clients/js/type-only-test/index.ts
  clients/js/type-only-test/package.json
  examples/truffle/.gitattributes
  examples/truffle/.gitignore
  examples/truffle/LICENSE
  examples/truffle/README.md
  examples/truffle/contracts/ConvertLib.sol
  examples/truffle/contracts/MetaCoin.sol
  examples/truffle/migrations/1_deploy_contracts.js
  examples/truffle/package.json
  examples/truffle/scripts/exercise.contract.js
  examples/truffle/test/TestMetaCoin.sol
  examples/truffle/test/metacoin.js
  examples/truffle/truffle-config.js
  pnpm-lock.yaml
Labels: p:1, dependencies, js

#196 Test reversion with custom errors & maximum view call size
  contracts/contracts/tests/SemanticTests.sol
  contracts/hardhat.config.ts
  contracts/test/semantics.ts
Labels: p:1, contracts

#217 contracts: add SHA384 hash and P-384 curve
  contracts/contracts/Sapphire.sol
  contracts/contracts/tests/HashTests.sol
  contracts/test/hashes.ts
  contracts/test/signing.ts
Labels: contracts

#205 contracts: add gaspad and gasused precompiles
  contracts/contracts/Sapphire.sol
  contracts/contracts/tests/Gas.sol
  contracts/test/gas.ts
Labels: contracts

#219 Fix missing build on publish
  .github/workflows/publish.yaml
Labels: p:0, js, client
