Repository oasisprotocol/sapphire-paratime, pull requests merged in 2024-08, with the labels that each got.

#360 contracts: silence SIWE Solidity tests compile warnings
  clients/py/requirements.txt
  contracts/contracts/tests/SiweParserTests.sol
Labels: contracts, solidity

#363 packaging: use PNPM for publishing, with correct tags
  .github/workflows/publish.yaml
Labels: javascript, packaging

#365 packaging: bump versions + add CHANGELOG entries
  clients/js/CHANGELOG.md
  clients/js/package.json
  integrations/ethers-v6/CHANGELOG.md
  integrations/ethers-v6/package.json
  integrations/hardhat/CHANGELOG.md
  integrations/hardhat/package.json
  integrations/viem-v2/CHANGELOG.md
  integrations/viem-v2/package.json
  integrations/wagmi-v2/CHANGELOG.md
  integrations/wagmi-v2/package.json
Labels: javascript, packaging

#368 packaging: fix for PNPM publish auth token
  .github/workflows/publish.yaml
  clients/js/package.json
Labels: javascript, packaging

#369 packaging: permissions necessary for provenance pubishing
  .github/workflows/publish.yaml
  clients/js/package.json
Labels: packaging

#364 docs: Add Band oracle addresses
  docs/addresses.md
Labels: docs

#370 contracts: add support for core.CallDataPublicKey and core.CurrentEpoch
  contracts/CHANGELOG.md
  contracts/contracts/Subcall.sol
  contracts/contracts/tests/SubcallTests.sol
  contracts/package.json
  contracts/test/subcall.ts
Labels: contracts

#349 readme: Update contributions
  CONTRIBUTING.md
Labels: p:2, docs
